language: bash

dist: xenial

services:
  - docker

before_script:
  # 登录到 docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # 这里编写测试代码的命令
  - echo "build hadoop-v2.6.4"

after_success:
  # 当代码测试通过后执行的命令
  - docker build -t gsakun/hadoop:v2.6.4 .
  - docker push gsakun/hadoop:v2.6.4
